INSERT INTO country_codes(name, code) VALUES
('Afghanistan', 'AFG'),
('Aland Islands', 'ALA'),
('Albania', 'ALB'),
('Algeria', 'DZA'),
('American Samoa', 'ASM'),
('Andorra', 'AND'),
('Angola', 'AGO'),
('Anguilla', 'AIA'),
('Antarctica', 'ATA'),
('Antigua and Barbuda', 'ATG'),
('Argentina', 'ARG'),
('Armenia', 'ARM'),
('Aruba', 'ABW'),
('Australia', 'AUS'),
('Austria', 'AUT'),
('Azerbaijan', 'AZE'),
('Bahamas', 'BHS'),
('Bahrain', 'BHR'),
('Bangladesh', 'BGD'),
('Barbados', 'BRB'),
('Belarus', 'BLR'),
('Belgium', 'BEL'),
('Belize', 'BLZ'),
('Benin', 'BEN'),
('Bermuda', 'BMU'),
('Bhutan', 'BTN'),
('Bolivia, Plurinational State of', 'BOL'),
('Bonaire, Saint Eustatius and Saba', 'BES'),
('Bosnia and Herzegovina', 'BIH'),
('Botswana', 'BWA'),
('Bouvet Island', 'BVT'),
('Brazil', 'BRA'),
('British Indian Ocean Territory', 'IOT'),
('Brunei Darussalam', 'BRN'),
('Bulgaria', 'BGR'),
('Burkina Faso', 'BFA'),
('Burundi', 'BDI'),
('Cambodia', 'KHM'),
('Cameroon', 'CMR'),
('Canada', 'CAN'),
('Cape Verde', 'CPV'),
('Cayman Islands', 'CYM'),
('Central African Republic', 'CAF'),
('Chad', 'TCD'),
('Chile', 'CHL'),
('China', 'CHN'),
('Christmas Island', 'CXR'),
('Cocos (Keeling) Islands', 'CCK'),
('Colombia', 'COL'),
('Czech Republic', 'CZE'),
('Latvia', 'LVA'),
('Russian Federation', 'RUS'),
('Ukraine', 'UKR'),
('Zimbabwe', 'ZWE');

GO
